import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Sophomore Caucus</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to the Sophomore Caucus website!
				</h1>
			</main>
		</>
	);
};

export default Home;
